services:
  - type: web
    name: estg-tss-server
    env: node
    buildCommand: npm install --prefix Server
    startCommand: npm start --prefix Server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
    plan: free

  - type: web
    name: estg-tss-client
    env: node
    buildCommand: |
      cd Client
      npm install
      npm run build
    staticPublishPath: "./Client/dist"
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://estg-tss-server.onrender.com
    plan: free
